changelog:
  exclude:
    labels: [skip-changelog]
  categories:
    - title: New features
      labels: [enhancement]
    - title: Calculation fixes
      labels: [calculation]
    - title: Bug fixes
      labels: [bug]
    - title: Interface
      labels: [ui]
    - title: Documentation
      labels: [documentation]
    - title: Maintenance
      labels: [dependencies, ci]
    - title: Other changes
      labels: ["*"]
